name: lint

on:
  push:
    branches: ['**']
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "go.*"
      - "**/*.go"
      - "testdata/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set pkgcraft dir env var
      run: echo pkgcraft_dir=~/pkgcraft >> $GITHUB_ENV

    - name: Download prebuilt pkgcraft-c library
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{ secrets.PKGCRAFT_CI_TOKEN }}
        repo: pkgcraft/pkgcraft
        branch: main
        workflow: pkgcraft-c.yml
        workflow_conclusion: ""
        search_artifacts: true
        name: pkgcraft-c-${{ runner.os }}
        path: ${{ env.pkgcraft_dir }}

    - name: Override build variables
      run: |
        echo "PKG_CONFIG_PATH=${pkgcraft_dir}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${pkgcraft_dir}" >> $GITHUB_ENV

    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.18.0'

    - name: Lint code
      uses: golangci/golangci-lint-action@v6
